### ISSUE TITLE
Milestone 01 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/CorrR#18]
Hello,
Thanks for your effort in the submission. You really did a really good job. I a few comments,
- You should fix the formatting error in the description file, as when I tried to install the package it threw that error message:
```
Malformed Authors@R field:
  <text>:1:92: unexpected ','
1: person("Mengda (Albert)", "Yu", email = "albertlife4913@gmail.com", role = c("aut", "cre")),
```
- Good job on using `Roxygen2` package in generating the function documentation templates.
- In the `corr_plus` function, the description says that the purpose of the function is to calculate the "relationship". I believe if you replace "relationship" with "correlation" will be better./
- Throughout the codes you always refer to "positive/negative" as "pos/neg", which may be confusing to some people.
- I couldn't find the `License` file.
- You did a great job in the tests.
- In the `test_std_plus`, should `Inf` be treated as `NA`?

**Comment by mru4913** [comment]
Hi Mohammed,

Thank you for your feedback.
- [x] we have fixed the formatting error in the description file.
- [x] we have updated the functions specification including corr_plus
- [ ] we will write positive/negative instead of pos/neg.
- [ ] We did not include the License file because in the next milestone we will have a lecture regarding which license is appropriate to our project. (would you @hsmohammed clarify this?)

>  * In the `test_std_plus`, should `Inf` be treated as `NA`? we will discuss the best way to solve this problem.

Thank you again.

**Comment by hsmohammed** [comment]
Regarding the license file, it's OK for now not to include it.

Thank you!

**Comment by K3ra-y** [comment]
Hi @hsmohammed 
Regarding the feedback: *In the `test_std_plus`, should `Inf` be treated as `NA`?*
It is addressed [here](https://github.com/UBC-MDS/CorrPy/commit/5093da5471a667565f49df2f6af5711136ce5efd) for CorrPy. 
Thank you for the feedback!
