### ISSUE TITLE
Milestone 3- R functions and tests (high priority)

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/CorrR#20]
# Functions 
The following summaries expectations for this milestone:
- 3 R function （by March 1st.)
- [x] std_plus (Done)
- [x] corr_plus (Done)
- [x] cov_mx 

Requirements:
- Update test cases 
- As you develop your code we also expect you to update your code documentation so that it makes sense with any of the changes you have made.

---

# Revisiting your test cases and writing additional test cases

You will be writing additional test cases for both your Python and R packages to make sure that your functions work as expected.

---

# Licence 

- [x] Adding a licence (Done)

**Comment by mru4913** [comment]
**Following GitHub Flow workflow**

Starting from this milestone, you must follow the GitHub Flow workflow. Each team member must do at least one review and each member must have some part of their code reviewed by other team members.
- [ ] Kera
- [ ] Krish 
- [ ] Wilson  
- [ ] Albert

 In particular, each team member will

- create a branch
- work on the function you are responsible for in this branch
- add commits
- open a pull request (you should be at this step by the end of the lab on Feb 12th)
- wait for the code review and feedback from other team member
- review code of other team member via their pull request
- deploy your changes
- merge if your branch is not causing any problems

---

Just some notes:
1. In order to improve our coding format, it is better to limit to 120 characters per line. For further information, please read https://stackoverflow.com/questions/88942/why-does-pep-8-specify-a-maximum-line-length-of-79-characters
2. To toggle the warning line in Studio. https://support.rstudio.com/hc/en-us/community/posts/207625357-Toggle-80-character-warning-line
3. For atom. https://stackoverflow.com/questions/49616864/limiting-line-length-in-atom
4. For VS code. https://stackoverflow.com/questions/29968499/vertical-rulers-in-visual-studio-code
