### ISSUE TITLE
Milestone 3 - Documentation in CorrR 

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/CorrR#22]
- Documentation
- [x] R package README (including usage and installation instructions)
`pip install git+PACKAGE_URL.git`
`devtools::install_github("PACKAGE_NAME")` for R packages
- [x] Code documentation 
- [x] ensure that the test suite for each function provides 100% branch coverage (if possible). Please include documentation (e.g. as we did on the board in class) that shows you've checked for this.
- [x] functions
- [x] tests
- [x] vignette (for R packages only)
