### ISSUE TITLE
Milestone 03 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/CorrR#38]
Hi,

Thanks for your efforts in milestone 03 submission. I've just reviewed your submission and I have few comments/suggestions below.

- [x] Your package installation runs without any problems 
- [x] You have provided very comprehensive test cases that I cannot think of any more 
- [x] You have provided a vignette for the R package 
- [x] You have provided an open source license 
- [x] You have provided good documentation of your function
- [x] You provided your branch coverage results

Thanks!
